import React from 'react';
import { Input } from '@/components/ui/input';
import { useAtom } from 'jotai';
import { visitDetailsAtom } from '@/lib/atoms';

const VisitDetailsForm = () => {
  const [visitDetails, setVisitDetails] = useAtom(visitDetailsAtom);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { id, value } = e.target;
    setVisitDetails((prev) => ({
      ...prev,
      [id === 'visit-id' ? 'visitId' :
       id === 'date-of-examination' ? 'visitDate' :
       id === 'time-of-examination' ? 'timeOfExamination' :
       id === 'doctor' ? 'doctor' :
       id === 'department' ? 'department' :
       id === 'generated-by' ? 'generatedBy' :
       id]: value,
    }));
  };

  return (
    <div className="p-4">
      <h2 className="text-2xl font-bold mb-4">Visit Details</h2>
      <hr className="border-t border-gray-300 my-4" />
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label htmlFor="visit-id" className="block text-sm font-bold text-gray-700 mb-1">Visit ID</label>
          <Input id="visit-id" placeholder="Enter Visit ID" className="h-10 py-2" value={visitDetails.visitId} onChange={handleChange} />
        </div>
        <div>
          <label htmlFor="date-of-examination" className="block text-sm font-bold text-gray-700 mb-1">Date of Examination</label>
          <Input id="date-of-examination" type="date" className="h-10 py-2" value={visitDetails.visitDate} onChange={handleChange} />
        </div>
        <div>
          <label htmlFor="time-of-examination" className="block text-sm font-bold text-gray-700 mb-1">Time of Examination</label>
          <Input id="time-of-examination" type="time" className="h-10 py-2" value={visitDetails.timeOfExamination} onChange={handleChange} />
        </div>
        <div>
          <label htmlFor="doctor" className="block text-sm font-bold text-gray-700 mb-1">Doctor</label>
          <select id="doctor" className="h-10 py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 block w-full sm:text-sm bg-white" value={visitDetails.doctor} onChange={handleChange}>
            <option value="">Select Doctor</option>
            <option value="dr-smith">Dr. Smith</option>
            <option value="dr-jones">Dr. Jones</option>
            <option value="dr-williams">Dr. Williams</option>
          </select>
        </div>
        <div>
          <label htmlFor="department" className="block text-sm font-bold text-gray-700 mb-1">Department</label>
          <Input id="department" placeholder="Enter Department" className="h-10 py-2" value={visitDetails.department} onChange={handleChange} />
        </div>
        <div>
          <label htmlFor="generated-by" className="block text-sm font-bold text-gray-700 mb-1">Generated By</label>
          <Input id="generated-by" placeholder="Generated By" className="h-10 py-2" value={visitDetails.generatedBy} onChange={handleChange} />
        </div>
      </div>
      <div className="flex justify-start mt-4">
        <button className="bg-blue-500 hover:cursor-pointer hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md">
          Send for Vitals
        </button>
      </div>
    </div>
  );
};

export default VisitDetailsForm; 